apiVersion: v1
kind: Pod
metadata:
  name: mypvcapp
  labels:
    app: web
    type: front-end
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /tmp
          name: data-volume
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: pvclaim

# Made with Bob
