apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-manager
  namespace: streamsets-dc
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "list", "watch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-manager-binding
  namespace: streamsets-dc
subjects:
- kind: ServiceAccount
  name: s1-control-agent
  namespace: streamsets-dc
roleRef:
  kind: Role
  name: secret-manager
  apiGroup: rbac.authorization.k8s.io

