apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myrcset
  labels:
    app: myrcset-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      name: mypod
      labels:
        app: front-end
    spec:
      containers:
        - name: mynginx
          image: nginx
          ports:
            - containerPort: 80

# Made with Bob
